# Generated by Django 4.0.5 on 2022-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('IdCurso', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id curso')),
                ('nombreCurso', models.TextField(max_length=30, verbose_name='Nombre del Curso')),
                ('Descripcion', models.TextField(verbose_name='Descripción del Curso')),
                ('activo', models.TextField(max_length=30, verbose_name='Estado del curso')),
                ('Cupo', models.PositiveSmallIntegerField(verbose_name='Cupos Disponibles')),
                ('FechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('FechaFinal', models.DateField(verbose_name='Fecha de Fin de curso')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-created'],
            },
        ),
    ]
