# Generated by Django 4.0.5 on 2022-06-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='activo',
        ),
    ]
