# Generated by Django 4.0.5 on 2022-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_cursos_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Comentario',
            field=models.TextField(default=1, max_length=30, verbose_name='Comentarios del Curso'),
            preserve_default=False,
        ),
    ]
