# Generated by Django 4.0.5 on 2022-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='duracion',
        ),
        migrations.AddField(
            model_name='cursos',
            name='cupo',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cupos Disponibles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='activo',
            field=models.TextField(max_length=30, verbose_name='Estado del curso'),
        ),
    ]
