# Generated by Django 4.0.5 on 2022-06-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_imagen_alter_cursos_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='duracion',
        ),
        migrations.AddField(
            model_name='cursos',
            name='cupo',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cupos disponibles'),
            preserve_default=False,
        ),
    ]
