# Generated by Django 4.0.5 on 2022-07-01 22:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('IdActividad', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id Actividad')),
                ('Nombre', models.TextField(max_length=30, verbose_name='Nombre de la Actividad')),
                ('Descripcion', models.TextField(verbose_name='Descripción de la Actividad')),
                ('ComentarioActividad', ckeditor.fields.RichTextField(verbose_name='Comentario de la Actividad')),
                ('FechaInicioActividad', models.DateField(verbose_name='Fecha de la Actividad')),
                ('FechaFinalActividad', models.DateField(verbose_name='Fecha de la Actividad')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Comentario',
            field=models.TextField(max_length=120, verbose_name='Comentarios del Curso'),
        ),
    ]
