# Generated by Django 4.0.5 on 2022-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_cursos_duracion_cursos_cupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='cupo',
            new_name='Cupo',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='nombreCurso',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='idcurso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='IdCurso',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False, verbose_name='Id curso'),
            preserve_default=False,
        ),
    ]
