# Generated by Django 4.0.5 on 2022-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_rename_cupo_cursos_cupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='activo',
        ),
        migrations.AddField(
            model_name='cursos',
            name='FechaInicio',
            field=models.DateField(default=1, verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
    ]
