# Generated by Django 4.0.5 on 2022-07-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_actividad_alter_cursos_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='ComentarioActividad',
            new_name='ComentActividad',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='Nombre',
            new_name='NombreActividad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='FechaFinalActividad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='FechaInicioActividad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='updated',
        ),
    ]
