# Generated by Django 4.0.5 on 2022-07-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_comentarioactividad_actividad_comentactividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='IdActividad',
            new_name='id',
        ),
    ]
